FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src
COPY [".", "."]
RUN dotnet restore "RebalancingBot.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "RebalancingBot.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "RebalancingBot.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
RUN apk update && \
    apk add --no-cache tzdata
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "RebalancingBot.dll"]
